version: '3'
services:
 web:
  build: 
   context: .
   dockerfile: Dockerfile.dev
  ports:
    - "3000:3000"
  volumes:
    - /new/node_modules
    - .:/new
 tests:
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - /new/node_modules
   - .:/new
  command: ["npm","run","test"] 
